apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::104711845692:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RVRVLQK6O34Z
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::104711845692:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-15T19:14:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1644"
  uid: 1ce7e4be-ec41-43aa-b2df-43e82b4f40dc

